spring.application.name=sgcf_back

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=frantonytest@gmail.com
spring.mail.password=

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/bdsgcf
spring.datasource.username=frantony07
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql= true


spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.h2.console.enabled=true

spring.web.error.include-message=always
