alter table "customer" alter column "id" add generated by default as identity;

alter table "employee" alter column "id" add generated by default as identity;

alter table "tour" alter column "id" add generated by default as identity;

alter table "user" alter column "id" add generated by default as identity;

alter table "password_reset" alter column "id" add generated by default as identity;

alter table "payment" alter column "id" add generated by default as identity;

alter table "quota" alter column "id" add generated by default as identity;

alter table "reservation" alter column "id" add generated by default as identity;
